// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1319);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1593981421);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c96e1531-66a7-4c16-93b1-e49f31a1b99f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1593981426525");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1593985026525");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1593981425");
user_pref("browser.slowStartup.averageTime", 4318);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200403170909");
user_pref("browser.startup.homepage_override.mstone", "75.0");
user_pref("browser.startup.lastColdStartupCheck", 1593981424);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1593981425684");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "75.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "701220617cad41cca6703a941b3d4421");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "75.0");
user_pref("extensions.lastPlatformVersion", "75.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"042d6558-ce81-4836-a675-6edd14332a03\",\"formautofill@mozilla.org\":\"e02a855d-f297-4484-a465-816047ed4731\",\"screenshots@mozilla.org\":\"ff350e38-d0f5-411d-8bdb-1e8d31c48b2c\",\"webcompat-reporter@mozilla.org\":\"7e34429c-ee11-412a-b320-d7d8e3924e72\",\"webcompat@mozilla.org\":\"ca14129a-32b9-46c1-8436-cd3b31cc54c7\",\"default-theme@mozilla.org\":\"f4cc3107-62e3-4f4c-9191-ca6d5b8b7a7a\",\"google@search.mozilla.org\":\"60af56ae-db7b-4d27-957d-41bf98efd95e\",\"amazondotcom@search.mozilla.org\":\"ff4bd665-53ef-43e4-8740-8c6f4a64be47\",\"bing@search.mozilla.org\":\"12c6321a-834a-4d07-9b90-171040008423\",\"ddg@search.mozilla.org\":\"9e9a06a5-9b2f-45d5-aa56-d43df1f7299f\",\"ebay@search.mozilla.org\":\"e2b2c4b3-323d-411c-96c2-957be49219cb\",\"twitter@search.mozilla.org\":\"adfccd4e-44ee-4d0c-a0d1-6b02f3cd2f78\",\"wikipedia@search.mozilla.org\":\"76342d61-83db-4b5d-8d00-abafe21147f3\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4c786582-e6a2-479f-b2a9-6d5e2e168c72");
user_pref("security.sandbox.plugin.tempDirSuffix", "5b0801f2-7213-45e2-9fb8-a79fb2318b71");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1593981419);
user_pref("toolkit.telemetry.cachedClientID", "7ce5b9d0-acd9-4bb7-9eae-6f4ea7837f45");
user_pref("toolkit.telemetry.previousBuildID", "20200403170909");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
